### ISSUE TITLE
Issues with Tera Data Parser

### ISSUE THREAD

**Issue by Feuerstahl** [tera-toolbox/tera-toolbox#31]
I've got the following Error Messages in the Chatlog.
What could be the issue and how to solve it?
I am using the latest version of Toolbox

`[17:38:34.363] [protocol] Error while compiling definition "C_START_CLIMBING.1":
[17:38:34.366] Error: Invalid data type "uint" for field "result.unk"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)
    at Server.<anonymous> (C:\TeraToolbox\bin\proxy.js:137:74)
[17:38:35.604] [protocol] Error while compiling definition "S_EACH_SKILL_RESULT.14":
[17:38:35.605] Error: Invalid data type "@include" for field "result.S_EACH_SKILL_RESULT.13.def"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)
    at Server.<anonymous> (C:\TeraToolbox\bin\proxy.js:137:74)
[17:38:36.199] [protocol] Error while compiling definition "S_ITEMLIST.3":
[17:38:36.200] Error: Invalid data type "@include" for field "result.S_ITEMLIST.1.def"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)
    at Server.<anonymous> (C:\TeraToolbox\bin\proxy.js:137:74)
[17:38:36.800] [protocol] Error while compiling definition "S_PLAYER_STAT_UPDATE.14":
[17:38:36.801] Error: Invalid data type "@include" for field "result.S_PLAYER_STAT_UPDATE.13.def"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)
    at Server.<anonymous> (C:\TeraToolbox\bin\proxy.js:137:74)
[17:38:37.105] [protocol] Error while compiling definition "S_REQUEST_SERVANT_INFO_LIST.3":
[17:38:37.106] Error: Invalid data type "@include" for field "result.S_REQUEST_SERVANT_INFO_LIST.2.def"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)
    at Server.<anonymous> (C:\TeraToolbox\bin\proxy.js:137:74)
[17:38:37.112] [protocol] Error while compiling definition "S_REQUEST_SPAWN_SERVANT.4":
[17:38:37.113] Error: Invalid data type "@include" for field "result.S_REQUEST_SPAWN_SERVANT.3.def"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)
    at Server.<anonymous> (C:\TeraToolbox\bin\proxy.js:137:74)
[17:38:37.800] [protocol] Error while compiling definition "S_TRADE_BROKER_HISTORY_ITEM_LIST.2":
[17:38:37.801] Error: Invalid data type "uint8" for field "tmpelem_offset_result_listings.unk3"!
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:102:31)
    at _transpileReader (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:167:44)
    at transpile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:568:20)
    at compile (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\compiler.js:583:24)
    at TeraProtocol.addDefinition (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:96:30)
    at TeraProtocol.loadCustomDefinitions (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:171:22)
    at TeraProtocol.load (C:\TeraToolbox\node_modules\tera-data-parser\lib\protocol\index.js:121:14)
    at new Dispatch (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:118:23)
    at new Connection (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js:21:25)
    at ConnectionManager.start (C:\TeraToolbox\bin\connectionManager.js:38:28)`

**Comment by Snugglez** [comment]
"Toolbox's advanced features are incompatible with legacy tera-proxy definitions"
